/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Exemplo8;

/**
 *
 * @author clebe
 */
public class Exemplo8_2 extends javax.swing.JFrame {

    /**
     * Creates new form Exemplo8_2
     */
    public Exemplo8_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmArquivo = new javax.swing.JMenu();
        jmExemplo8_4 = new javax.swing.JMenu();
        jmExemplo8_3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmExemplo8_5 = new javax.swing.JMenuItem();
        jmExemplo8_9 = new javax.swing.JMenuItem();
        jmExemplo8_8 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmArquivo.setMnemonic('a');
        jmArquivo.setText("Arquivo");
        jMenuBar1.add(jmArquivo);

        jmExemplo8_4.setMnemonic('e');
        jmExemplo8_4.setText("Exemplos");

        jmExemplo8_3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, 0));
        jmExemplo8_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/java.png"))); // NOI18N
        jmExemplo8_3.setText("Exemplo8_3");
        jmExemplo8_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmExemplo8_3ActionPerformed(evt);
            }
        });
        jmExemplo8_4.add(jmExemplo8_3);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/java.png"))); // NOI18N
        jMenuItem2.setText("Exemplo8_4");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmExemplo8_4.add(jMenuItem2);

        jmExemplo8_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/java.png"))); // NOI18N
        jmExemplo8_5.setText("Exemplo8_5");
        jmExemplo8_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmExemplo8_5ActionPerformed(evt);
            }
        });
        jmExemplo8_4.add(jmExemplo8_5);

        jmExemplo8_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/java.png"))); // NOI18N
        jmExemplo8_9.setText("Exemplo8_9");
        jmExemplo8_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmExemplo8_9ActionPerformed(evt);
            }
        });
        jmExemplo8_4.add(jmExemplo8_9);

        jmExemplo8_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/java.png"))); // NOI18N
        jmExemplo8_8.setText("Exemplo8_8");
        jmExemplo8_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmExemplo8_8ActionPerformed(evt);
            }
        });
        jmExemplo8_4.add(jmExemplo8_8);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/java.png"))); // NOI18N
        jMenuItem1.setText("Exemplo8_10");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmExemplo8_4.add(jMenuItem1);

        jMenuBar1.add(jmExemplo8_4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmExemplo8_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmExemplo8_3ActionPerformed
        Exemplo8_3 exemplo3 = new Exemplo8_3();
        exemplo3.setVisible(true);
    }//GEN-LAST:event_jmExemplo8_3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Exemplo8_4 exemplo4 = new Exemplo8_4();
        exemplo4.setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmExemplo8_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmExemplo8_5ActionPerformed
        Exemplo8_5 exemplo5 = new Exemplo8_5();
        exemplo5.setVisible(true);

    }//GEN-LAST:event_jmExemplo8_5ActionPerformed

    private void jmExemplo8_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmExemplo8_8ActionPerformed
        Exemplo8_8 exemplo8 = new Exemplo8_8();
        exemplo8.setVisible(true);

    }//GEN-LAST:event_jmExemplo8_8ActionPerformed

    private void jmExemplo8_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmExemplo8_9ActionPerformed
        Exemplo8_9 exemplo9 = new Exemplo8_9();
        exemplo9.setVisible(true);

    }//GEN-LAST:event_jmExemplo8_9ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
  Exemplo8_10 exemplo10 = new Exemplo8_10();
        exemplo10.setVisible(true);    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exemplo8_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exemplo8_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exemplo8_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exemplo8_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exemplo8_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu jmArquivo;
    private javax.swing.JMenuItem jmExemplo8_3;
    private javax.swing.JMenu jmExemplo8_4;
    private javax.swing.JMenuItem jmExemplo8_5;
    private javax.swing.JMenuItem jmExemplo8_8;
    private javax.swing.JMenuItem jmExemplo8_9;
    // End of variables declaration//GEN-END:variables
}
