/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Exemplo8;

import javax.swing.JOptionPane;

/**
 *
 * @author Geral
 */
public class Exemplo8_12 extends javax.swing.JFrame {

    /**
     * Creates new form Exemplo8_12
     */
    public Exemplo8_12() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jrSimNao = new javax.swing.JRadioButton();
        jrSimNaoCancelar = new javax.swing.JRadioButton();
        jrOkCancelar = new javax.swing.JRadioButton();
        JBmMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonGroup1.add(jrSimNao);
        jrSimNao.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jrSimNao.setText("Sim e Não");

        buttonGroup1.add(jrSimNaoCancelar);
        jrSimNaoCancelar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jrSimNaoCancelar.setText("Sim, Não e Cancelar");

        buttonGroup1.add(jrOkCancelar);
        jrOkCancelar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jrOkCancelar.setText("Ok e Cancelar");

        JBmMostrar.setBackground(new java.awt.Color(51, 255, 51));
        JBmMostrar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        JBmMostrar.setText("MOSTRAR");
        JBmMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBmMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JBmMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrSimNaoCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrOkCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrSimNao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jrSimNao)
                .addGap(27, 27, 27)
                .addComponent(jrSimNaoCancelar)
                .addGap(31, 31, 31)
                .addComponent(jrOkCancelar)
                .addGap(45, 45, 45)
                .addComponent(JBmMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBmMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBmMostrarActionPerformed
        int resp = 0;
        if(jrSimNao.isSelected()){
            resp = JOptionPane.showConfirmDialog(null, "Erro ao acessar o arquivo. Tentar novamente?", "Erro de Arquivo", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }else  if(jrSimNaoCancelar.isSelected()){
            resp = JOptionPane.showConfirmDialog(null, "Deseja salvar as alterações?", "Salvar o arquivo", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        }else {
            resp = JOptionPane.showConfirmDialog(null, "Deseja abrir o Arquivo?", "Abrir o arquivo", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        }
        JOptionPane.showMessageDialog(null, resp, "Resposta",1);
    }//GEN-LAST:event_JBmMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exemplo8_12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exemplo8_12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exemplo8_12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exemplo8_12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exemplo8_12().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBmMostrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jrOkCancelar;
    private javax.swing.JRadioButton jrSimNao;
    private javax.swing.JRadioButton jrSimNaoCancelar;
    // End of variables declaration//GEN-END:variables
}
