/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Exemplo8;

import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Geral
 */
public class Exemplos8_15 extends javax.swing.JFrame {

    /**
     * Creates new form Exemplos8_15
     */
    public Exemplos8_15() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jbAmentar = new javax.swing.JButton();
        jbDiminuir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jProgressBar1.setBackground(new java.awt.Color(204, 204, 204));
        jProgressBar1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jProgressBar1.setForeground(new java.awt.Color(204, 204, 204));
        jProgressBar1.setStringPainted(true);

        jbAmentar.setBackground(new java.awt.Color(102, 255, 0));
        jbAmentar.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jbAmentar.setText("+");
        jbAmentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAmentarActionPerformed(evt);
            }
        });

        jbDiminuir.setBackground(new java.awt.Color(255, 51, 51));
        jbDiminuir.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jbDiminuir.setText("-");
        jbDiminuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDiminuirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jbAmentar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbDiminuir, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbDiminuir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAmentar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(67, 67, 67))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbAmentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAmentarActionPerformed
        new Thread(){
        public void run(){
            for (int i = 0; i < 101; i++) {
                try {
                    sleep(100);
                    jProgressBar1.setValue(i);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Exemplos8_15.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            
        }
        //jProgressBar1.setValue(jProgressBar1.getValue() + 5);
        }.start();
    }//GEN-LAST:event_jbAmentarActionPerformed

    private void jbDiminuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDiminuirActionPerformed
        new Thread(){
        public void run(){
            for (int i = jProgressBar1.getValue(); i > 101; i--) {
                try {
                    sleep(100);
                    jProgressBar1.setValue(i);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Exemplos8_15.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            
        }
        //jProgressBar1.setValue(jProgressBar1.getValue() + 5);
        }.start();
    }//GEN-LAST:event_jbDiminuirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exemplos8_15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exemplos8_15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exemplos8_15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exemplos8_15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exemplos8_15().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JButton jbAmentar;
    private javax.swing.JButton jbDiminuir;
    // End of variables declaration//GEN-END:variables
}
